version: "3.9"
services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: "rapradiptya/whatsapp-go:latest"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: "always"
    ports:
      - "3000:3000"
